In [1]:
import pandas as pd

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
nasa=pd.read_csv(r"C:\Users\ritik\Downloads\nasa\nasa.csv")

In [5]:
nasa.shape

(4687, 40)

In [6]:
nasa.head()

,Neo Reference ID,Name,Absolute Magnitude,Est Dia in KM(min),Est Dia in KM(max),Est Dia in M(min),Est Dia in M(max),Est Dia in Miles(min),Est Dia in Miles(max),Est Dia in Feet(min),...,Asc Node Longitude,Orbital Period,Perihelion Distance,Perihelion Arg,Aphelion Dist,Perihelion Time,Mean Anomaly,Mean Motion,Unnamed: 38,Hazardous
0,3703080,3703080,21.6,0.127220,0.284472,127.219878,284.472296,0.079051,0.176763,417.388066,...,314.373913,609.599786,0.808259,57.257470,2.005764,2458161.642,264.837533,0.590551,NaN,True
1,3723955,3723955,21.3,0.146068,0.326618,146.067964,326.617897,0.090762,0.202951,479.225620,...,136.717242,425.869294,0.718200,313.091975,1.497352,2457794.969,173.741112,0.845330,NaN,False
2,2446862,2446862,20.3,0.231502,0.517654,231.502122,517.654482,0.143849,0.321655,759.521423,...,259.475979,643.580228,0.950791,248.415038,1.966857,2458120.468,292.893654,0.559371,NaN,True
3,3092506,3092506,27.4,0.008801,0.019681,8.801465,19.680675,0.005469,0.012229,28.876199,...,57.173266,514.082140,0.983902,18.707701,1.527904,2457902.337,68.741007,0.700277,NaN,False
4,3514799,3514799,21.6,0.127220,0.284472,127.219878,284.472296,0.079051,0.176763,417.388066,...,84.629307,495.597821,0.967687,158.263596,1.483543,2457814.455,135.142133,0.726395,NaN,True

In [7]:
from pandas.tseries import converter
converter.register()

c:\users\ritik\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: 'pandas.tseries.converter.register' has been moved and renamed to 'pandas.plotting.register_matplotlib_converters'.

In [8]:
Z=pd.read_csv(r"C:\Users\ritik\Downloads\nasa\nasa.csv")

In [9]:
Z.drop(['Hazardous'], axis = 1)

,Neo Reference ID,Name,Absolute Magnitude,Est Dia in KM(min),Est Dia in KM(max),Est Dia in M(min),Est Dia in M(max),Est Dia in Miles(min),Est Dia in Miles(max),Est Dia in Feet(min),...,Inclination,Asc Node Longitude,Orbital Period,Perihelion Distance,Perihelion Arg,Aphelion Dist,Perihelion Time,Mean Anomaly,Mean Motion,Unnamed: 38
0,3703080,3703080,21.600,0.127220,0.284472,127.219878,284.472296,0.079051,0.176763,417.388066,...,6.025981,314.373913,609.599786,0.808259,57.257470,2.005764,2458161.642,264.837533,0.590551,NaN
1,3723955,3723955,21.300,0.146068,0.326618,146.067964,326.617897,0.090762,0.202951,479.225620,...,28.412996,136.717242,425.869294,0.718200,313.091975,1.497352,2457794.969,173.741112,0.845330,NaN
2,2446862,2446862,20.300,0.231502,0.517654,231.502122,517.654482,0.143849,0.321655,759.521423,...,4.237961,259.475979,643.580228,0.950791,248.415038,1.966857,2458120.468,292.893654,0.559371,NaN
3,3092506,3092506,27.400,0.008801,0.019681,8.801465,19.680675,0.005469,0.012229,28.876199,...,7.905894,57.173266,514.082140,0.983902,18.707701,1.527904,2457902.337,68.741007,0.700277,NaN
4,3514799,3514799,21.600,0.127220,0.284472,127.219878,284.472296,0.079051,0.176763,417.388066,...,16.793382,84.629307,495.597821,0.967687,158.263596,1.483543,2457814.455,135.142133,0.726395,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4682,3759007,3759007,23.900,0.044112,0.098637,44.111820,98.637028,0.027410,0.061290,144.723824,...,39.880491,164.183305,457.179984,0.741558,276.395697,1.581299,2457708.228,304.306025,0.787436,NaN
4683,3759295,3759295,28.200,0.006089,0.013616,6.089126,13.615700,0.003784,0.008460,19.977449,...,5.360249,345.225230,407.185767,0.996434,42.111064,1.153835,2458087.617,282.978786,0.884117,NaN
4684,3759714,3759714,22.700,0.076658,0.171412,76.657557,171.411509,0.047633,0.106510,251.501181,...,4.405467,37.026468,690.054279,0.965760,274.692712,2.090708,2458300.480,203.501147,0.521698,NaN
4685,3759720,3759720,21.800,0.116026,0.259442,116.025908,259.441818,0.072095,0.161210,380.662441,...,21.080244,163.802909,662.048343,1.185467,180.346090,1.787733,2458288.261,203.524965,0.543767,NaN
4686,3772978,3772978,19.109,0.400641,0.895860,400.640617,895.859655,0.248946,0.556661,1314.437764,...,53.574922,187.642183,653.679098,0.876110,222.436688,2.071980,2458318.587,184.820424,0.550729,NaN

In [10]:
Z.drop([20])

,Neo Reference ID,Name,Absolute Magnitude,Est Dia in KM(min),Est Dia in KM(max),Est Dia in M(min),Est Dia in M(max),Est Dia in Miles(min),Est Dia in Miles(max),Est Dia in Feet(min),...,Asc Node Longitude,Orbital Period,Perihelion Distance,Perihelion Arg,Aphelion Dist,Perihelion Time,Mean Anomaly,Mean Motion,Unnamed: 38,Hazardous
0,3703080,3703080,21.600,0.127220,0.284472,127.219878,284.472296,0.079051,0.176763,417.388066,...,314.373913,609.599786,0.808259,57.257470,2.005764,2458161.642,264.837533,0.590551,NaN,True
1,3723955,3723955,21.300,0.146068,0.326618,146.067964,326.617897,0.090762,0.202951,479.225620,...,136.717242,425.869294,0.718200,313.091975,1.497352,2457794.969,173.741112,0.845330,NaN,False
2,2446862,2446862,20.300,0.231502,0.517654,231.502122,517.654482,0.143849,0.321655,759.521423,...,259.475979,643.580228,0.950791,248.415038,1.966857,2458120.468,292.893654,0.559371,NaN,True
3,3092506,3092506,27.400,0.008801,0.019681,8.801465,19.680675,0.005469,0.012229,28.876199,...,57.173266,514.082140,0.983902,18.707701,1.527904,2457902.337,68.741007,0.700277,NaN,False
4,3514799,3514799,21.600,0.127220,0.284472,127.219878,284.472296,0.079051,0.176763,417.388066,...,84.629307,495.597821,0.967687,158.263596,1.483543,2457814.455,135.142133,0.726395,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4682,3759007,3759007,23.900,0.044112,0.098637,44.111820,98.637028,0.027410,0.061290,144.723824,...,164.183305,457.179984,0.741558,276.395697,1.581299,2457708.228,304.306025,0.787436,NaN,False
4683,3759295,3759295,28.200,0.006089,0.013616,6.089126,13.615700,0.003784,0.008460,19.977449,...,345.225230,407.185767,0.996434,42.111064,1.153835,2458087.617,282.978786,0.884117,NaN,False
4684,3759714,3759714,22.700,0.076658,0.171412,76.657557,171.411509,0.047633,0.106510,251.501181,...,37.026468,690.054279,0.965760,274.692712,2.090708,2458300.480,203.501147,0.521698,NaN,False
4685,3759720,3759720,21.800,0.116026,0.259442,116.025908,259.441818,0.072095,0.161210,380.662441,...,163.802909,662.048343,1.185467,180.346090,1.787733,2458288.261,203.524965,0.543767,NaN,False
4686,3772978,3772978,19.109,0.400641,0.895860,400.640617,895.859655,0.248946,0.556661,1314.437764,...,187.642183,653.679098,0.876110,222.436688,2.071980,2458318.587,184.820424,0.550729,NaN,False

In [11]:
y=pd.read_csv(r"C:\Users\ritik\Downloads\nasa\nasa.csv" ,usecols = ['Hazardous'])

In [12]:
Z['Close_Approach_Date'] = pd.to_datetime(Z.Close_Approach_Date)

In [13]:
Z['Orbit_Determination_Date'] = pd.to_datetime(Z.Orbit_Determination_Date)

In [26]:
Z.iloc[0,:]

Absolute Magnitude                            21.6
Est Dia in KM(min)                         0.12722
Est Dia in KM(max)                        0.284472
Est Dia in M(min)                           127.22
Est Dia in M(max)                          284.472
                                           ...
Orbit_Determination_Is_quarter_end           False
Orbit_Determination_Is_quarter_start         False
Orbit_Determination_Is_year_end              False
Orbit_Determination_Is_year_start            False
Orbit_Determination_Elapsed             1491467760
Name: 0, Length: 62, dtype: object

In [15]:
from fastai.tabular import add_datepart

In [16]:
import torch
from pandas.api.types import is_numeric_dtype
from datetime import date, datetime
import calendar

In [17]:
add_datepart(Z,'Close_Approach_Date')

,Neo Reference ID,Name,Absolute Magnitude,Est Dia in KM(min),Est Dia in KM(max),Est Dia in M(min),Est Dia in M(max),Est Dia in Miles(min),Est Dia in Miles(max),Est Dia in Feet(min),...,Close_Approach_Day,Close_Approach_Dayofweek,Close_Approach_Dayofyear,Close_Approach_Is_month_end,Close_Approach_Is_month_start,Close_Approach_Is_quarter_end,Close_Approach_Is_quarter_start,Close_Approach_Is_year_end,Close_Approach_Is_year_start,Close_Approach_Elapsed
0,3703080,3703080,21.600,0.127220,0.284472,127.219878,284.472296,0.079051,0.176763,417.388066,...,1,6,1,False,True,False,True,False,True,788918400
1,3723955,3723955,21.300,0.146068,0.326618,146.067964,326.617897,0.090762,0.202951,479.225620,...,1,6,1,False,True,False,True,False,True,788918400
2,2446862,2446862,20.300,0.231502,0.517654,231.502122,517.654482,0.143849,0.321655,759.521423,...,8,6,8,False,False,False,False,False,False,789523200
3,3092506,3092506,27.400,0.008801,0.019681,8.801465,19.680675,0.005469,0.012229,28.876199,...,15,6,15,False,False,False,False,False,False,790128000
4,3514799,3514799,21.600,0.127220,0.284472,127.219878,284.472296,0.079051,0.176763,417.388066,...,15,6,15,False,False,False,False,False,False,790128000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4682,3759007,3759007,23.900,0.044112,0.098637,44.111820,98.637028,0.027410,0.061290,144.723824,...,8,3,252,False,False,False,False,False,False,1473292800
4683,3759295,3759295,28.200,0.006089,0.013616,6.089126,13.615700,0.003784,0.008460,19.977449,...,8,3,252,False,False,False,False,False,False,1473292800
4684,3759714,3759714,22.700,0.076658,0.171412,76.657557,171.411509,0.047633,0.106510,251.501181,...,8,3,252,False,False,False,False,False,False,1473292800
4685,3759720,3759720,21.800,0.116026,0.259442,116.025908,259.441818,0.072095,0.161210,380.662441,...,8,3,252,False,False,False,False,False,False,1473292800
4686,3772978,3772978,19.109,0.400641,0.895860,400.640617,895.859655,0.248946,0.556661,1314.437764,...,8,3,252,False,False,False,False,False,False,1473292800

In [18]:
add_datepart(Z,'Orbit_Determination_Date')

,Neo Reference ID,Name,Absolute Magnitude,Est Dia in KM(min),Est Dia in KM(max),Est Dia in M(min),Est Dia in M(max),Est Dia in Miles(min),Est Dia in Miles(max),Est Dia in Feet(min),...,Orbit_Determination_Day,Orbit_Determination_Dayofweek,Orbit_Determination_Dayofyear,Orbit_Determination_Is_month_end,Orbit_Determination_Is_month_start,Orbit_Determination_Is_quarter_end,Orbit_Determination_Is_quarter_start,Orbit_Determination_Is_year_end,Orbit_Determination_Is_year_start,Orbit_Determination_Elapsed
0,3703080,3703080,21.600,0.127220,0.284472,127.219878,284.472296,0.079051,0.176763,417.388066,...,6,3,96,False,False,False,False,False,False,1491467760
1,3723955,3723955,21.300,0.146068,0.326618,146.067964,326.617897,0.090762,0.202951,479.225620,...,6,3,96,False,False,False,False,False,False,1491467520
2,2446862,2446862,20.300,0.231502,0.517654,231.502122,517.654482,0.143849,0.321655,759.521423,...,6,3,96,False,False,False,False,False,False,1491470400
3,3092506,3092506,27.400,0.008801,0.019681,8.801465,19.680675,0.005469,0.012229,28.876199,...,6,3,96,False,False,False,False,False,False,1491470100
4,3514799,3514799,21.600,0.127220,0.284472,127.219878,284.472296,0.079051,0.176763,417.388066,...,6,3,96,False,False,False,False,False,False,1491469020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4682,3759007,3759007,23.900,0.044112,0.098637,44.111820,98.637028,0.027410,0.061290,144.723824,...,6,3,96,False,False,False,False,False,False,1491467040
4683,3759295,3759295,28.200,0.006089,0.013616,6.089126,13.615700,0.003784,0.008460,19.977449,...,6,3,96,False,False,False,False,False,False,1491466980
4684,3759714,3759714,22.700,0.076658,0.171412,76.657557,171.411509,0.047633,0.106510,251.501181,...,6,3,96,False,False,False,False,False,False,1491466980
4685,3759720,3759720,21.800,0.116026,0.259442,116.025908,259.441818,0.072095,0.161210,380.662441,...,6,3,96,False,False,False,False,False,False,1491466980
4686,3772978,3772978,19.109,0.400641,0.895860,400.640617,895.859655,0.248946,0.556661,1314.437764,...,29,5,119,False,False,False,False,False,False,1493446680

In [19]:
Z.fillna(Z.mean(), inplace=True)
Z.replace([np.inf, -np.inf], np.nan, inplace=True)

In [37]:
from sklearn.model_selection import train_test_split
Z_train, Z_test, y_train, y_test = train_test_split(Z, y, test_size = 0.20)

ValueError: Found input variables with inconsistent numbers of samples: [0, 4687]

In [31]:
Z.head()

,index,Neo Reference ID,Name,Absolute Magnitude,Est Dia in KM(min),Est Dia in KM(max),Est Dia in M(min),Est Dia in M(max),Est Dia in Miles(min),Est Dia in Miles(max),...,Orbit_Determination_Day,Orbit_Determination_Dayofweek,Orbit_Determination_Dayofyear,Orbit_Determination_Is_month_end,Orbit_Determination_Is_month_start,Orbit_Determination_Is_quarter_end,Orbit_Determination_Is_quarter_start,Orbit_Determination_Is_year_end,Orbit_Determination_Is_year_start,Orbit_Determination_Elapsed
0,0,3703080,3703080,21.6,0.127220,0.284472,127.219878,284.472296,0.079051,0.176763,...,6,3,96,False,False,False,False,False,False,1491467760
1,1,3723955,3723955,21.3,0.146068,0.326618,146.067964,326.617897,0.090762,0.202951,...,6,3,96,False,False,False,False,False,False,1491467520
2,2,2446862,2446862,20.3,0.231502,0.517654,231.502122,517.654482,0.143849,0.321655,...,6,3,96,False,False,False,False,False,False,1491470400
3,3,3092506,3092506,27.4,0.008801,0.019681,8.801465,19.680675,0.005469,0.012229,...,6,3,96,False,False,False,False,False,False,1491470100
4,4,3514799,3514799,21.6,0.127220,0.284472,127.219878,284.472296,0.079051,0.176763,...,6,3,96,False,False,False,False,False,False,1491469020

In [36]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(Z_train, y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [28]:
np.any(np.isnan(Z))

np.all(np.isfinite(Z))

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [33]:
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

Empty DataFrame
Columns: [index, Neo Reference ID, Name, Absolute Magnitude, Est Dia in KM(min), Est Dia in KM(max), Est Dia in M(min), Est Dia in M(max), Est Dia in Miles(min), Est Dia in Miles(max), Est Dia in Feet(min), Est Dia in Feet(max), Epoch Date Close Approach, Relative Velocity km per sec, Relative Velocity km per hr, Miles per hour, Miss Dist.(Astronomical), Miss Dist.(lunar), Miss Dist.(kilometers), Miss Dist.(miles), Unnamed: 20, Orbit ID, Orbit Uncertainity, Minimum Orbit Intersection, Jupiter Tisserand Invariant, Epoch Osculation, Eccentricity, Semi Major Axis, Inclination, Asc Node Longitude, Orbital Period, Perihelion Distance, Perihelion Arg, Aphelion Dist, Perihelion Time, Mean Anomaly, Mean Motion, Unnamed: 38, Hazardous, Close_Approach_Year, Close_Approach_Month, Close_Approach_Week, Close_Approach_Day, Close_Approach_Dayofweek, Close_Approach_Dayofyear, Close_Approach_Is_month_end, Close_Approach_Is_month_start, Close_Approach_Is_quarter_end, Close_Approach_Is_quarter_start, Close_Approach_Is_year_end, Close_Approach_Is_year_start, Close_Approach_Elapsed, Orbit_Determination_Year, Orbit_Determination_Month, Orbit_Determination_Week, Orbit_Determination_Day, Orbit_Determination_Dayofweek, Orbit_Determination_Dayofyear, Orbit_Determination_Is_month_end, Orbit_Determination_Is_month_start, Orbit_Determination_Is_quarter_end, Orbit_Determination_Is_quarter_start, Orbit_Determination_Is_year_end, Orbit_Determination_Is_year_start, Orbit_Determination_Elapsed]
Index: []

[0 rows x 65 columns]

In [35]:
Z.head()

Empty DataFrame
Columns: [index, Neo Reference ID, Name, Absolute Magnitude, Est Dia in KM(min), Est Dia in KM(max), Est Dia in M(min), Est Dia in M(max), Est Dia in Miles(min), Est Dia in Miles(max), Est Dia in Feet(min), Est Dia in Feet(max), Epoch Date Close Approach, Relative Velocity km per sec, Relative Velocity km per hr, Miles per hour, Miss Dist.(Astronomical), Miss Dist.(lunar), Miss Dist.(kilometers), Miss Dist.(miles), Unnamed: 20, Orbit ID, Orbit Uncertainity, Minimum Orbit Intersection, Jupiter Tisserand Invariant, Epoch Osculation, Eccentricity, Semi Major Axis, Inclination, Asc Node Longitude, Orbital Period, Perihelion Distance, Perihelion Arg, Aphelion Dist, Perihelion Time, Mean Anomaly, Mean Motion, Unnamed: 38, Hazardous, Close_Approach_Year, Close_Approach_Month, Close_Approach_Week, Close_Approach_Day, Close_Approach_Dayofweek, Close_Approach_Dayofyear, Close_Approach_Is_month_end, Close_Approach_Is_month_start, Close_Approach_Is_quarter_end, Close_Approach_Is_quarter_start, Close_Approach_Is_year_end, Close_Approach_Is_year_start, Close_Approach_Elapsed, Orbit_Determination_Year, Orbit_Determination_Month, Orbit_Determination_Week, Orbit_Determination_Day, Orbit_Determination_Dayofweek, Orbit_Determination_Dayofyear, Orbit_Determination_Is_month_end, Orbit_Determination_Is_month_start, Orbit_Determination_Is_quarter_end, Orbit_Determination_Is_quarter_start, Orbit_Determination_Is_year_end, Orbit_Determination_Is_year_start, Orbit_Determination_Elapsed]
Index: []

[0 rows x 65 columns]